### ISSUE TITLE
Attribute decode_responses not present into AsyncConnection object

### ISSUE THREAD

**Issue by piraz** [coldnight/gredis#1]
I'm not able to run gredis on python 3.6 tornado 4.5.2. 

This is the demo code I'm trying to run:

```
from tornado import gen
from tornado import web
from gredis.client import AsyncRedis
import tornado.ioloop

client = AsyncRedis("localhost", 6379)


class DemoHandler(web.RequestHandler):

    @gen.coroutine
    def get(self):
        ret = yield client.incr("test")
        redis = client.to_blocking_client()
        ret2 = redis.incr("key")
        self.write(str(ret+ret2))


def make_app():
    return web.Application([
        (r"/", DemoHandler),
    ])

if __name__ == "__main__":
    app = make_app()
    app.listen(8888)
    tornado.ioloop.IOLoop.current().start()
```

Here is the error I'm facing:

```
/home/user1/python/asredisenv/bin/python /home/user1/source/examples/asredis/asredis/__init__.py
ERROR:tornado.application:Uncaught exception GET / (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Host': 'localhost:8888', 'Connection': 'keep-alive', 'Cache-Control': 'max-age=0', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Upgrade-Insecure-Requests': '1', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en-US,en;q=0.9,pt-BR;q=0.8,pt;q=0.7,fr;q=0.6'})
Traceback (most recent call last):
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/web.py", line 1511, in _execute
    result = yield result
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/user1/source/examples/asredis/asredis/__init__.py", line 13, in get
    ret = yield client.incr("test")
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/gredis/client.py", line 42, in execute_command
    yield connection.send_command(*args)
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/gredis/connection.py", line 279, in send_command
    yield self.send_packed_command(self.pack_command(*args))
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/gredis/connection.py", line 253, in send_packed_command
    yield self.connect()
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/gredis/connection.py", line 211, in connect
    yield self.on_connect()
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/gredis/connection.py", line 223, in on_connect
    self._parser.on_connect(self)
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/gredis/connection.py", line 115, in on_connect
    if connection.decode_responses:
AttributeError: 'AsyncConnection' object has no attribute 'decode_responses'
ERROR:tornado.access:500 GET / (127.0.0.1) 19.44ms
```

The error occurs on connection.py, line 111:
```
    def on_connect(self, connection):
        """ Called when stream connects """
        self._stream = weakref.proxy(connection._stream)
        self._buffer = StreamBuffer(self._stream, self.socket_read_size)
        if connection.decode_responses:
            self.encoding = connection.encoding
```

After adding decode_responses and encoding parameter to the connection object, this error will occur:

```
ERROR:tornado.application:Uncaught exception GET / (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Host': 'localhost:8888', 'Connection': 'keep-alive', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache', 'Upgrade-Insecure-Requests': '1', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'en-US,en;q=0.9,pt-BR;q=0.8,pt;q=0.7,fr;q=0.6'})
Traceback (most recent call last):
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/web.py", line 1511, in _execute
    result = yield result
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/user1/source/examples/asredis/asredis/__init__.py", line 13, in get
    ret = yield client.incr("test")
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/gredis/client.py", line 43, in execute_command
    result = yield self.parse_response(connection, command_name, **options)
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/gredis/client.py", line 57, in parse_response
    response = yield connection.read_response()
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/gredis/connection.py", line 295, in read_response
    response = yield self._parser.read_response()
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/gredis/connection.py", line 134, in read_response
    response = yield self._buffer.readline()
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/gredis/connection.py", line 85, in readline
    yield self._read_from_stream()
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/gredis/connection.py", line 43, in _read_from_stream
    data = yield self._stream.read_until_regex('\r\n')
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/iostream.py", line 256, in read_until_regex
    self._try_inline_read()
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/iostream.py", line 705, in _try_inline_read
    pos = self._find_read_pos()
  File "/home/user1/python/asredisenv/lib/python3.6/site-packages/tornado/iostream.py", line 815, in _find_read_pos
    self._read_buffer_pos)
TypeError: cannot use a string pattern on a bytes-like object
ERROR:tornado.access:500 GET / (127.0.0.1) 7.67ms
```

**Comment by coldnight** [comment]
Thanks for your report, but if you use Python 3.6, I will recommend you to use [aioredis](https://github.com/aio-libs/aioredis) based on `asyncio`, with that you can use `async def` and `await` syntax. And you can integrate Tornado with asyncio too, see also: http://www.tornadoweb.org/en/stable/asyncio.html.

**Comment by piraz** [comment]
Hey! It seems like this is working fine. So the issue was related to the redis client version?

I'm working on a framework over tornado that organize things in components. The framework gives you session layer and configurable data sources.

One data source type is redis and you can plug that to the session layer. I'm trying to unblock everything on the framework right now. I support python 2.7 and python 3.x.

You are the second guy that pointed me to a aiosomething lib. Should I go for that option right now?

I think this is gonna be tricky on python 2.7 right?

I'm trying this on the framework and probably your lib is being shipped on the next release. Should I don't use it and go for aioredis instead?

**Comment by coldnight** [comment]
Yes, this library just extends the redis client.  And aioredis just worked Python 3.5 and 3.6.

I don't think the session layer need asynchronous connection, the Redis is fast, so synchronous connection is ok.

This library created for long-polling request, such as chat service in demo.

**Comment by coldnight** [comment]
And I have used aioredis in my own project for long-polling request with Python 3.6.
